# Generated by Django 5.2.4 on 2025-08-04 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
